### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by DanGdl** [Eden-Sheiko/Quadratic-Equation#1]
1. https://github.com/Eden-Sheiko/Quadratic-Equation/blob/ee969412464a34099a28a36e057ff1d2fe637bec/Equation.cpp#L46 -> rename Equation::discriminant_calculator() to something more informative, like void Equation::find_roots(), Equation::find_solutions(), Equation::solve()

2. https://github.com/Eden-Sheiko/Quadratic-Equation/blob/ee969412464a34099a28a36e057ff1d2fe637bec/Equation.cpp#L76 -> you can move this condition into method discriminant_calculator() and remove method update_solutions_for_discriminant()

**Comment by Eden-Sheiko** [comment]
the name was changed to find_roots() 
and the condition was moved inside of find_roots()
documentation was also updated

**Comment by DanGdl** [comment]
https://github.com/Eden-Sheiko/Quadratic-Equation/blob/5d69a0109688590e2bfbeae3c966d9d23b2b6476/Equation.cpp#L20 -> don't catch it here. use try-catch in unit test

**Comment by Eden-Sheiko** [comment]
the assignment said that I needed to deal with it, so I caught the exception and dealt with it in order to prevent a memory leak
"A should never be zero! If there's an attempt to construct an Equation with a=0 or set
its value later to zero, the code should throw std::invalid_argument (from the <stdexcept
> library). (be careful of constructor memory leaking if the exception is caught)"
